### ISSUE TITLE
Percentile rank is wrong

### ISSUE THREAD

**Issue by morxa** [fedora-infra/tahrir#357] opened 2016-12-09 09:07 UTC
The computed percentile rank is wrong. As an example, on my [profile](https://badges.fedoraproject.org/user/thofmann), it says:

> Ranked 287 out of 43354 ranked users (top 0.01%).

My calculator tells me that this should be 0.66%.

Originally reported as fedora-infra/fedbadges#51.

**Comment by pypingou** [comment] 2016-12-09 09:18
I believe this is a duplicate of https://github.com/fedora-infra/tahrir/issues/355

So closing as such, thanks for the report though :)

**Closed by pypingou** 2016-12-09 09:18 UTC
