### ISSUE TITLE
Badges not working on Fedora Badges account

### ISSUE THREAD

**Issue by jessicachitas** [fedora-infra/tahrir#456] opened 2022-05-02 18:33 UTC
Opening this ticket as on my Fedora Badges account, my badges aren't being displayed. I have closed multiple tickets since my account was open and I haven't got any badges from it.
Hope we can find a solution to this and let me know if you need more info! Thanks!

**Comment by jessicachitas** [comment] 2022-05-02 18:34
My username as well on Fedora Badges is jesschitas

**Comment by jessicachitas** [comment] 2022-05-02 18:34
![Screenshot from 2022-04-27 20-59-00](https://user-images.githubusercontent.com/36636982/166304973-6052974b-5d49-4a15-a719-173eee9b5b89.png)
This is my profile at present as well

**Comment by nirik** [comment] 2022-05-05 20:28
Note, I am pretty sure that this is caused by badges querying the _old_ account system for users, so it doesn't recognize anyone added after we switched to the new account system. ;( 

Badges needs to move to query the new account system to fix this I am pretty sure.

**Comment by mscherer** [comment] 2022-05-05 21:45
So duplicate of https://github.com/fedora-infra/tahrir/issues/454 ?

**Comment by nirik** [comment] 2022-05-05 21:51
Yeah, could be indeed.

**Closed as completed** 2024-04-03 21:21 UTC
