### ISSUE TITLE
Badge "You Can Pry It From My Cold, Undead Hands" wasn't awarded

### ISSUE THREAD

**Issue by yarda** [fedora-infra/tahrir#458] opened 2022-06-07 12:56 UTC
Hi,

I did [1], but I wasn't awarded badge [2]. Taking into account it was awarded last time in 2018, I think the badge doesn't work.

[1] https://src.fedoraproject.org/rpms/sdrangel/c/f07eca772b037b608f86f513586f847d0e61ee05?branch=f34
[2] https://badges.fedoraproject.org/badge/you-can-pry-it-from-my-cold%2C-undead-hands

**Comment by mscherer** [comment] 2022-06-07 15:09
Likely duplicate of #454

**Closed as completed** 2024-04-03 21:21 UTC
