### ISSUE TITLE
White rabbit badge not working

### ISSUE THREAD

**Issue by yarda** [fedora-infra/tahrir#457] opened 2022-06-07 10:57 UTC
Hi,

I wasn't awarded the White rabbit badge [1] for setting the timezone in the FAS. I also tried switching timezone Europe/Prague -> UTC -> Europe/Prague and Europe/Prague -> Europe/Paris -> Europe/Prague. It's cca. 24 hours and still no badge was awarded. It seems there are more people with the problem, maybe the badge isn't working at all, i.e. it was last awarded more than a year ago, which is quite a long time and suspicious (Last awarded to[ sayaksarkar ](https://badges.fedoraproject.org/user/sayaksarkar)on 2021-04-12).

[1] https://badges.fedoraproject.org/badge/white-rabbit

**Comment by mscherer** [comment] 2022-06-07 15:09
Duplicate of #454

**Closed as completed** 2024-04-03 21:21 UTC
